"use client"

import { motion, useInView } from "framer-motion"
import { useRef, useEffect, useState } from "react"
import { Sparkles, Check, ArrowRight } from "lucide-react"

const codeOutput = `// Generated by ProductOS Code Agent

import { prisma } from '@/lib/db'
import { validateUser } from '@/lib/auth'

export async function POST(req: Request) {
  const session = await validateUser()
  const data = await req.json()
  
  const user = await prisma.user.create({
    data: {
      email: data.email,
      name: data.name,
      role: 'user'
    }
  })
  
  return Response.json({ user })
}`

const stages = [
  { label: "Understanding context", duration: 800 },
  { label: "Generating code", duration: 2000 },
  { label: "Validating types", duration: 600 },
  { label: "Ready to deploy", duration: 400 },
]

export function AgentCodeStream() {
  const ref = useRef(null)
  const isInView = useInView(ref, { once: true, margin: "-100px" })
  const [currentStage, setCurrentStage] = useState(-1)
  const [displayedCode, setDisplayedCode] = useState("")
  const [isComplete, setIsComplete] = useState(false)

  useEffect(() => {
    if (!isInView) return

    // Start stages
    let stageTimeout: NodeJS.Timeout
    let charIndex = 0
    let codeInterval: NodeJS.Timer

    const runStages = (stageIndex: number) => {
      if (stageIndex >= stages.length) {
        setIsComplete(true)
        return
      }

      setCurrentStage(stageIndex)

      // Stage 1 (generating code) - type out the code
      if (stageIndex === 1) {
        codeInterval = setInterval(() => {
          if (charIndex < codeOutput.length) {
            setDisplayedCode(codeOutput.slice(0, charIndex + 1))
            charIndex++
          } else {
            clearInterval(codeInterval)
          }
        }, 8)
      }

      stageTimeout = setTimeout(() => {
        runStages(stageIndex + 1)
      }, stages[stageIndex].duration)
    }

    // Start after a brief delay
    const initialTimeout = setTimeout(() => runStages(0), 300)

    return () => {
      clearTimeout(initialTimeout)
      clearTimeout(stageTimeout)
      if (codeInterval) clearInterval(codeInterval)
    }
  }, [isInView])

  return (
    <div ref={ref} className="relative">
      <div className="grid lg:grid-cols-[1fr,auto,1fr] gap-6 items-start">
        {/* Agent status panel */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          animate={isInView ? { opacity: 1, x: 0 } : {}}
          transition={{ duration: 0.5 }}
          className="relative rounded-xl border border-border/50 bg-card/50 backdrop-blur-sm overflow-hidden"
        >
          {/* Subtle glow */}
          <div className="absolute inset-0 bg-gradient-to-br from-violet-500/5 via-transparent to-transparent pointer-events-none" />
          
          {/* Header */}
          <div className="flex items-center gap-3 px-4 py-3 border-b border-border/30">
            <div className="relative">
              <Sparkles className="w-4 h-4 text-violet-400" />
              {currentStage >= 0 && !isComplete && (
                <motion.div
                  animate={{ scale: [1, 1.5, 1], opacity: [0.5, 0, 0.5] }}
                  transition={{ duration: 1.5, repeat: Infinity }}
                  className="absolute inset-0 rounded-full bg-violet-400"
                />
              )}
            </div>
            <span className="text-sm font-medium text-foreground">Code Agent</span>
          </div>

          {/* Stages */}
          <div className="p-4 space-y-3">
            {stages.map((stage, index) => (
              <motion.div
                key={stage.label}
                initial={{ opacity: 0.3 }}
                animate={{ 
                  opacity: index <= currentStage ? 1 : 0.3,
                }}
                className="flex items-center gap-3"
              >
                <div className={`
                  w-5 h-5 rounded-full flex items-center justify-center text-xs
                  ${index < currentStage 
                    ? 'bg-emerald-500/20 text-emerald-500' 
                    : index === currentStage
                      ? 'bg-violet-500/20 text-violet-400'
                      : 'bg-muted/50 text-muted-foreground/50'
                  }
                `}>
                  {index < currentStage ? (
                    <Check className="w-3 h-3" />
                  ) : index === currentStage ? (
                    <motion.div
                      animate={{ rotate: 360 }}
                      transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                      className="w-2 h-2 border border-current border-t-transparent rounded-full"
                    />
                  ) : (
                    <span>{index + 1}</span>
                  )}
                </div>
                <span className={`text-sm ${
                  index <= currentStage ? 'text-foreground' : 'text-muted-foreground/50'
                }`}>
                  {stage.label}
                </span>
              </motion.div>
            ))}
          </div>
        </motion.div>

        {/* Arrow connector - desktop only */}
        <div className="hidden lg:flex items-center justify-center self-center">
          <motion.div
            initial={{ opacity: 0, scale: 0.8 }}
            animate={isInView ? { opacity: 1, scale: 1 } : {}}
            transition={{ delay: 0.3, duration: 0.4 }}
            className="w-10 h-10 rounded-full bg-card border border-border/50 flex items-center justify-center"
          >
            <ArrowRight className="w-4 h-4 text-muted-foreground" />
          </motion.div>
        </div>

        {/* Code output panel */}
        <motion.div
          initial={{ opacity: 0, x: 20 }}
          animate={isInView ? { opacity: 1, x: 0 } : {}}
          transition={{ duration: 0.5, delay: 0.2 }}
          className="relative rounded-xl border border-border/50 bg-[#0a0a0c] overflow-hidden"
        >
          {/* Header */}
          <div className="flex items-center justify-between px-4 py-3 border-b border-white/[0.06]">
            <div className="flex items-center gap-3">
              <div className="flex gap-1.5">
                <div className="w-2.5 h-2.5 rounded-full bg-white/10" />
                <div className="w-2.5 h-2.5 rounded-full bg-white/10" />
                <div className="w-2.5 h-2.5 rounded-full bg-white/10" />
              </div>
              <span className="text-xs text-white/40 font-mono">route.ts</span>
            </div>
            
            {isComplete && (
              <motion.div
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                className="flex items-center gap-1.5 px-2 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20"
              >
                <Check className="w-3 h-3 text-emerald-500" />
                <span className="text-xs text-emerald-400">Ready</span>
              </motion.div>
            )}
          </div>

          {/* Code content */}
          <div className="p-4 font-mono text-xs min-h-[240px] max-h-[320px] overflow-y-auto">
            <pre className="text-white/60 whitespace-pre-wrap">
              <code>{displayedCode}</code>
              {currentStage === 1 && (
                <motion.span
                  animate={{ opacity: [1, 0] }}
                  transition={{ duration: 0.4, repeat: Infinity }}
                  className="inline-block w-1.5 h-3.5 bg-violet-400 ml-0.5 align-middle"
                />
              )}
            </pre>
          </div>
        </motion.div>
      </div>

      {/* Deploy CTA */}
      {isComplete && (
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="flex items-center justify-center mt-6"
        >
          <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            className="flex items-center gap-2 px-5 py-2.5 rounded-lg bg-foreground text-background text-sm font-medium"
          >
            Deploy to Production
            <ArrowRight className="w-4 h-4" />
          </motion.button>
        </motion.div>
      )}
    </div>
  )
}
