"use client"

import { useState } from "react"
import { 
  Lightbulb, 
  Search, 
  FileText, 
  Palette, 
  Code,
  ArrowRight,
  Sparkles,
  Check,
  MessageSquare,
  Target,
  Users,
  BarChart3,
  Layers,
  Play,
  GitBranch,
  Terminal
} from "lucide-react"
import { cn } from "@/lib/utils"
import { motion, AnimatePresence } from "framer-motion"

type Stage = "ideate" | "discover" | "define" | "design" | "develop"

const stages = [
  { id: "ideate" as Stage, name: "Ideate", icon: Lightbulb, color: "sky" },
  { id: "discover" as Stage, name: "Discover", icon: Search, color: "violet" },
  { id: "define" as Stage, name: "Define", icon: FileText, color: "teal" },
  { id: "design" as Stage, name: "Design", icon: Palette, color: "purple" },
  { id: "develop" as Stage, name: "Develop", icon: Code, color: "amber" },
]

const stageColors = {
  sky: { bg: "bg-sky-500/10", text: "text-sky-400", border: "border-sky-500/20", solid: "bg-sky-500" },
  violet: { bg: "bg-violet-500/10", text: "text-violet-400", border: "border-violet-500/20", solid: "bg-violet-500" },
  teal: { bg: "bg-teal-500/10", text: "text-teal-400", border: "border-teal-500/20", solid: "bg-teal-500" },
  purple: { bg: "bg-purple-500/10", text: "text-purple-400", border: "border-purple-500/20", solid: "bg-purple-500" },
  amber: { bg: "bg-amber-500/10", text: "text-amber-400", border: "border-amber-500/20", solid: "bg-amber-500" },
}

// Content for each stage
const stageContent = {
  ideate: {
    title: "Capture Your Vision",
    subtitle: "Turn rough ideas into structured concepts with AI assistance",
    items: [
      { icon: MessageSquare, label: "Describe your idea in natural language", status: "active" },
      { icon: Target, label: "AI identifies core value proposition", status: "pending" },
      { icon: Sparkles, label: "Generate multiple concept variations", status: "pending" },
    ],
    chat: {
      user: "I want to build an AI-powered analytics dashboard for SaaS companies",
      assistant: "Great idea! Let me help you shape this. Key questions:\n\n1. What metrics matter most to your users?\n2. Real-time or historical focus?\n3. Target company size?\n\nI'll generate 3 concept variations once you clarify these."
    }
  },
  discover: {
    title: "Market Research",
    subtitle: "AI agents analyze competitors, market size, and opportunities",
    items: [
      { icon: Search, label: "Competitor analysis: 12 products found", status: "complete" },
      { icon: BarChart3, label: "Market size: $4.2B TAM identified", status: "complete" },
      { icon: Users, label: "User interviews: 8 insights gathered", status: "active" },
    ],
    insights: [
      { title: "Market Gap", desc: "No solution combines real-time + predictive analytics for SMBs" },
      { title: "Price Point", desc: "Competitors charge $49-299/mo. Sweet spot: $79/mo" },
      { title: "Key Feature", desc: "Automated anomaly detection is highly requested" },
    ]
  },
  define: {
    title: "Product Requirements",
    subtitle: "AI-generated PRD with user stories and success metrics",
    items: [
      { icon: FileText, label: "PRD Document", status: "complete" },
      { icon: Users, label: "8 User Stories", status: "complete" },
      { icon: Target, label: "Success Metrics", status: "complete" },
    ],
    prd: {
      sections: ["Executive Summary", "Problem Statement", "User Personas", "Feature List", "Success Metrics"],
      currentSection: "Feature List",
      features: [
        "Real-time dashboard with 15+ widget types",
        "Automated anomaly detection with Slack alerts",
        "Custom report builder with scheduling",
        "Team collaboration with comments",
      ]
    }
  },
  design: {
    title: "UI Generation",
    subtitle: "AI creates responsive, production-ready interfaces",
    items: [
      { icon: Layers, label: "Wireframes generated", status: "complete" },
      { icon: Palette, label: "High-fidelity mockups", status: "active" },
      { icon: Play, label: "Interactive prototype", status: "pending" },
    ],
    screens: [
      { name: "Dashboard", status: "Ready", color: "emerald" },
      { name: "Analytics", status: "In Progress", color: "amber" },
      { name: "Settings", status: "Queued", color: "slate" },
      { name: "Reports", status: "Queued", color: "slate" },
    ]
  },
  develop: {
    title: "Code Generation",
    subtitle: "Production-ready Next.js code with tests",
    items: [
      { icon: Code, label: "Next.js 14 + TypeScript", status: "complete" },
      { icon: GitBranch, label: "GitHub repo created", status: "complete" },
      { icon: Terminal, label: "Deploying to Vercel...", status: "active" },
    ],
    code: `// Generated by ProductOS
export async function Dashboard() {
  const metrics = await getMetrics()
  
  return (
    <div className="grid gap-4">
      <StatsCard data={metrics} />
      <AnomalyAlert threshold={0.8} />
      <RealtimeChart stream={true} />
    </div>
  )
}`,
    stats: { files: 47, tests: 24, coverage: "94%" }
  }
}

export function InteractiveDashboard() {
  const [activeStage, setActiveStage] = useState<Stage>("ideate")
  const currentStage = stages.find(s => s.id === activeStage)!
  const colors = stageColors[currentStage.color as keyof typeof stageColors]
  const content = stageContent[activeStage]

  return (
    <div 
      className="relative rounded-xl overflow-hidden border border-border/50 dark:border-white/[0.08] bg-card dark:bg-[#0a0a0b]"
      style={{
        boxShadow: `
          0 0 0 1px rgba(0, 0, 0, 0.03),
          0 25px 50px -12px rgba(0, 0, 0, 0.25),
          0 50px 100px -20px rgba(0, 0, 0, 0.2)
        `
      }}
    >
      <div className="flex h-[450px] sm:h-[500px] lg:h-[520px]">
        {/* Sidebar */}
        <div className="w-56 lg:w-64 border-r border-border/50 dark:border-white/[0.06] bg-muted/30 dark:bg-[#0f0f10] flex-shrink-0 hidden sm:flex flex-col">
          {/* Logo */}
          <div className="p-4 border-b border-border/50 dark:border-white/[0.06]">
            <div className="flex items-center gap-2.5">
              <svg viewBox="0 0 36 36" fill="none" className="w-7 h-7">
                <path d="M4 32 L18 4 L32 32 Z" className="fill-foreground/80 dark:fill-[#E5E5E5]"/>
                <path d="M18 4 L4 32 L18 32 Z" className="fill-foreground/60 dark:fill-[#B3B3B3]"/>
                <path d="M18 4 L18 32 L32 4 Z" className="fill-foreground/40 dark:fill-[#808080]"/>
              </svg>
              <div>
                <div className="font-semibold text-sm text-foreground dark:text-white">ProductOS</div>
                <div className="text-[10px] text-muted-foreground dark:text-white/40">Workspace</div>
              </div>
            </div>
          </div>
          
          {/* Create button */}
          <div className="p-3">
            <div className="flex items-center gap-2">
              <button className="flex-1 h-9 rounded-lg bg-foreground dark:bg-white text-background dark:text-black text-sm font-medium hover:opacity-90 transition-opacity">
                Create New
              </button>
              <button className="h-9 w-9 rounded-lg border border-border dark:border-white/10 flex items-center justify-center hover:bg-muted dark:hover:bg-white/[0.04] transition-colors">
                <Search className="w-4 h-4 text-muted-foreground dark:text-white/50" />
              </button>
            </div>
          </div>
          
          {/* Stages - Interactive */}
          <div className="px-3 py-2">
            <div className="text-[10px] uppercase tracking-wider text-muted-foreground/70 dark:text-white/30 font-medium mb-2 px-2">Stages</div>
            <nav className="space-y-0.5">
              {stages.map((stage) => {
                const isActive = activeStage === stage.id
                const stageColor = stageColors[stage.color as keyof typeof stageColors]
                return (
                  <button 
                    key={stage.id}
                    onClick={() => setActiveStage(stage.id)}
                    className={cn(
                      "w-full flex items-center gap-3 px-2 py-2 rounded-md text-sm transition-all duration-200",
                      isActive 
                        ? `${stageColor.bg} ${stageColor.text} font-medium` 
                        : "text-foreground/70 dark:text-white/60 hover:bg-muted dark:hover:bg-white/[0.04]"
                    )}
                  >
                    <stage.icon className={cn("w-4 h-4", isActive ? stageColor.text : `text-${stage.color}-500 dark:text-${stage.color}-400`)} />
                    <span>{stage.name}</span>
                    {isActive && (
                      <div className={cn("ml-auto w-1.5 h-1.5 rounded-full", stageColor.solid)} />
                    )}
                  </button>
                )
              })}
            </nav>
          </div>
          
          {/* Theme toggle */}
          <div className="mt-auto p-3 border-t border-border/50 dark:border-white/[0.06]">
            <div className="flex items-center justify-between px-2 mb-3">
              <span className="text-xs text-muted-foreground dark:text-white/40">Theme</span>
              <div className="flex items-center gap-1 p-1 rounded-full bg-muted dark:bg-white/[0.04]">
                <div className="w-5 h-5 rounded-full flex items-center justify-center text-muted-foreground dark:text-white/30 dark:hidden bg-background shadow-sm">
                  <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z" clipRule="evenodd"/></svg>
                </div>
                <div className="hidden dark:flex w-5 h-5 rounded-full bg-white/10 items-center justify-center text-white">
                  <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 20 20"><path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z"/></svg>
                </div>
              </div>
            </div>
            
            {/* Credits */}
            <div className="px-2 py-2 rounded-lg bg-muted/50 dark:bg-white/[0.02] border border-border/50 dark:border-white/[0.04]">
              <div className="flex items-center justify-between mb-2">
                <span className="text-[10px] uppercase tracking-wider text-muted-foreground/70 dark:text-white/30 font-medium">Credits</span>
                <span className="text-sm font-semibold text-foreground dark:text-white">50</span>
              </div>
              <div className="h-1.5 rounded-full bg-muted dark:bg-white/[0.06] overflow-hidden">
                <div className="h-full w-1/2 rounded-full bg-gradient-to-r from-sky-500 to-violet-500" />
              </div>
            </div>
            
            {/* User */}
            <div className="flex items-center gap-2.5 mt-3 px-2">
              <div className="w-8 h-8 rounded-full bg-gradient-to-br from-amber-500 to-orange-600 flex items-center justify-center text-xs font-bold text-white">
                A
              </div>
              <div>
                <div className="text-sm text-foreground dark:text-white font-medium">Ariv</div>
                <div className="text-[10px] text-muted-foreground dark:text-white/40">ariv@1labs.ai</div>
              </div>
            </div>
          </div>
        </div>
        
        {/* Main content - Dynamic based on stage */}
        <div className="flex-1 flex flex-col bg-background dark:bg-[#0a0a0b] overflow-hidden">
          {/* Top bar with stage indicator */}
          <div className="flex items-center justify-between px-6 py-3 border-b border-border/50 dark:border-white/[0.06]">
            <div className="flex items-center gap-3">
              <span className={cn("px-2 py-1 rounded-md text-xs font-medium", colors.bg, colors.text)}>
                {currentStage.name}
              </span>
              <span className="text-sm font-medium text-foreground dark:text-white">{content.title}</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="flex items-center gap-1 px-2 py-1 rounded-md bg-emerald-500/10 text-emerald-500 text-xs">
                <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
                <span>AI Active</span>
              </div>
            </div>
          </div>
          
          {/* Stage content */}
          <div className="flex-1 p-6 overflow-hidden">
            <AnimatePresence mode="wait">
              <motion.div
                key={activeStage}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                transition={{ duration: 0.2 }}
                className="h-full"
              >
                {/* Ideate Stage */}
                {activeStage === "ideate" && (
                  <div className="space-y-4 h-full flex flex-col">
                    <p className="text-sm text-muted-foreground dark:text-white/50">{content.subtitle}</p>
                    
                    {/* Progress items */}
                    <div className="space-y-2">
                      {stageContent.ideate.items.map((item, i) => (
                        <div key={i} className={cn(
                          "flex items-center gap-3 p-2 rounded-lg text-sm",
                          item.status === "active" ? "bg-sky-500/10 text-sky-400" : 
                          item.status === "complete" ? "text-muted-foreground" : "text-muted-foreground/50"
                        )}>
                          {item.status === "complete" ? <Check className="w-4 h-4 text-emerald-500" /> : <item.icon className="w-4 h-4" />}
                          <span>{item.label}</span>
                          {item.status === "active" && <div className="ml-auto w-1.5 h-1.5 rounded-full bg-sky-500 animate-pulse" />}
                        </div>
                      ))}
                    </div>
                    
                    {/* Chat preview */}
                    <div className="flex-1 rounded-lg border border-border/50 dark:border-white/[0.06] bg-muted/20 dark:bg-white/[0.02] p-4 space-y-3 overflow-hidden">
                      <div className="flex items-start gap-2">
                        <div className="w-6 h-6 rounded-full bg-gradient-to-br from-amber-500 to-orange-600 flex items-center justify-center text-[10px] font-bold text-white flex-shrink-0">H</div>
                        <div className="text-sm text-foreground/80 dark:text-white/80">{stageContent.ideate.chat.user}</div>
                      </div>
                      <div className="flex items-start gap-2">
                        <div className="w-6 h-6 rounded-full bg-sky-500 flex items-center justify-center flex-shrink-0">
                          <Sparkles className="w-3 h-3 text-white" />
                        </div>
                        <div className="text-sm text-foreground/70 dark:text-white/70 whitespace-pre-line">{stageContent.ideate.chat.assistant}</div>
                      </div>
                    </div>
                  </div>
                )}

                {/* Discover Stage */}
                {activeStage === "discover" && (
                  <div className="space-y-4 h-full flex flex-col">
                    <p className="text-sm text-muted-foreground dark:text-white/50">{content.subtitle}</p>
                    
                    {/* Progress items */}
                    <div className="space-y-2">
                      {stageContent.discover.items.map((item, i) => (
                        <div key={i} className={cn(
                          "flex items-center gap-3 p-2 rounded-lg text-sm",
                          item.status === "active" ? "bg-violet-500/10 text-violet-400" : 
                          item.status === "complete" ? "text-emerald-500" : "text-muted-foreground/50"
                        )}>
                          {item.status === "complete" ? <Check className="w-4 h-4" /> : <item.icon className="w-4 h-4" />}
                          <span>{item.label}</span>
                          {item.status === "active" && <div className="ml-auto w-1.5 h-1.5 rounded-full bg-violet-500 animate-pulse" />}
                        </div>
                      ))}
                    </div>
                    
                    {/* Insights */}
                    <div className="flex-1 grid grid-cols-1 lg:grid-cols-3 gap-3">
                      {stageContent.discover.insights.map((insight, i) => (
                        <div key={i} className="p-3 rounded-lg border border-border/50 dark:border-white/[0.06] bg-muted/20 dark:bg-white/[0.02]">
                          <div className="text-xs text-violet-400 font-medium mb-1">{insight.title}</div>
                          <div className="text-sm text-foreground/80 dark:text-white/80">{insight.desc}</div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Define Stage */}
                {activeStage === "define" && (
                  <div className="space-y-4 h-full flex flex-col">
                    <p className="text-sm text-muted-foreground dark:text-white/50">{content.subtitle}</p>
                    
                    {/* PRD sections */}
                    <div className="flex gap-2 flex-wrap">
                      {stageContent.define.prd.sections.map((section) => (
                        <span 
                          key={section}
                          className={cn(
                            "px-2 py-1 rounded text-xs",
                            section === stageContent.define.prd.currentSection 
                              ? "bg-teal-500/10 text-teal-400 font-medium" 
                              : "bg-muted/50 dark:bg-white/[0.04] text-muted-foreground"
                          )}
                        >
                          {section}
                        </span>
                      ))}
                    </div>
                    
                    {/* Features list */}
                    <div className="flex-1 rounded-lg border border-border/50 dark:border-white/[0.06] bg-muted/20 dark:bg-white/[0.02] p-4">
                      <div className="text-xs text-teal-400 font-medium mb-3">Feature List (4 items)</div>
                      <div className="space-y-2">
                        {stageContent.define.prd.features.map((feature, i) => (
                          <div key={i} className="flex items-center gap-2 text-sm text-foreground/80 dark:text-white/80">
                            <Check className="w-3.5 h-3.5 text-teal-500 flex-shrink-0" />
                            <span>{feature}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                )}

                {/* Design Stage */}
                {activeStage === "design" && (
                  <div className="space-y-4 h-full flex flex-col">
                    <p className="text-sm text-muted-foreground dark:text-white/50">{content.subtitle}</p>
                    
                    {/* Progress items */}
                    <div className="space-y-2">
                      {stageContent.design.items.map((item, i) => (
                        <div key={i} className={cn(
                          "flex items-center gap-3 p-2 rounded-lg text-sm",
                          item.status === "active" ? "bg-purple-500/10 text-purple-400" : 
                          item.status === "complete" ? "text-emerald-500" : "text-muted-foreground/50"
                        )}>
                          {item.status === "complete" ? <Check className="w-4 h-4" /> : <item.icon className="w-4 h-4" />}
                          <span>{item.label}</span>
                          {item.status === "active" && <div className="ml-auto w-1.5 h-1.5 rounded-full bg-purple-500 animate-pulse" />}
                        </div>
                      ))}
                    </div>
                    
                    {/* Screens grid */}
                    <div className="flex-1 grid grid-cols-2 lg:grid-cols-4 gap-3">
                      {stageContent.design.screens.map((screen) => (
                        <div key={screen.name} className="p-3 rounded-lg border border-border/50 dark:border-white/[0.06] bg-muted/20 dark:bg-white/[0.02]">
                          <div className="aspect-video bg-muted/50 dark:bg-white/[0.04] rounded mb-2 flex items-center justify-center">
                            <Layers className="w-6 h-6 text-muted-foreground/30" />
                          </div>
                          <div className="text-sm font-medium text-foreground/80 dark:text-white/80">{screen.name}</div>
                          <div className={cn(
                            "text-[10px] mt-1",
                            screen.color === "emerald" ? "text-emerald-400" :
                            screen.color === "amber" ? "text-amber-400" : "text-muted-foreground"
                          )}>{screen.status}</div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Develop Stage */}
                {activeStage === "develop" && (
                  <div className="space-y-4 h-full flex flex-col">
                    <p className="text-sm text-muted-foreground dark:text-white/50">{content.subtitle}</p>
                    
                    {/* Progress items */}
                    <div className="space-y-2">
                      {stageContent.develop.items.map((item, i) => (
                        <div key={i} className={cn(
                          "flex items-center gap-3 p-2 rounded-lg text-sm",
                          item.status === "active" ? "bg-amber-500/10 text-amber-400" : 
                          item.status === "complete" ? "text-emerald-500" : "text-muted-foreground/50"
                        )}>
                          {item.status === "complete" ? <Check className="w-4 h-4" /> : <item.icon className="w-4 h-4" />}
                          <span>{item.label}</span>
                          {item.status === "active" && <div className="ml-auto w-1.5 h-1.5 rounded-full bg-amber-500 animate-pulse" />}
                        </div>
                      ))}
                    </div>
                    
                    {/* Code preview */}
                    <div className="flex-1 rounded-lg border border-border/50 dark:border-white/[0.06] bg-[#0d0d0e] overflow-hidden">
                      <div className="flex items-center justify-between px-3 py-2 border-b border-white/[0.06] bg-white/[0.02]">
                        <span className="text-xs text-muted-foreground">dashboard.tsx</span>
                        <div className="flex items-center gap-3 text-[10px] text-muted-foreground">
                          <span>{stageContent.develop.stats.files} files</span>
                          <span>{stageContent.develop.stats.tests} tests</span>
                          <span className="text-emerald-400">{stageContent.develop.stats.coverage} coverage</span>
                        </div>
                      </div>
                      <pre className="p-3 text-xs font-mono text-foreground/70 dark:text-white/70 overflow-auto">
                        <code>{stageContent.develop.code}</code>
                      </pre>
                    </div>
                  </div>
                )}
              </motion.div>
            </AnimatePresence>
          </div>
        </div>
      </div>
    </div>
  )
}
